### ISSUE TITLE
Processing in chunks

### ISSUE THREAD

**Issue by JohnV7** [paninski-lab/yass#25]
Hi,
I want to process data in chunks of 0.1 sec with a sampling rate of 30000. There are some issues with this:
1) If I set batch_size:3000 in the yaml file it is ignored.
2) If I calculate the max_memory such that batch_size=3000 then this works but I get an error `NameError: global name 'CONFIG' is not defined`  line 174 in preprocessing.py: `if get_score == 1 and CONFIG.spikes.detection == 'nn':`
3) If I side-track the CONFIG error then preprocessing works but then I get following error:
`ValueError: could not broadcast input array from shape (50000,5,10) into shape (1239,5,10)`  line 69 in score.py: `score[counter_batch:(counter_batch+nbuff)] = score_temp`

Best,
John

**Comment by JohnV7** [comment]
thanks a lot for fixing it. Regarding the batch processing, I want actually to apply YASS online (on streaming data), thus I want to use small chunks of 50-100 ms. Do you see any problem with this?

**Comment by jinhyunglee** [comment]
Yass visits the recording 3 times. (detecting spikes, making templates, deconvolution). We can make it to be truly online but it requires some development.

Or do you mean by running full pipeline on each small chunk?

**Comment by jinhyunglee** [comment]
I will dig into your issue #3 little bit more soon and let you know

**Comment by JohnV7** [comment]
ok, great, thanks. I meant truly online. So far, for testing purposes and before going to real experiments, I want to emulate the online case by reading sequentially small chunks from a file, thus establishing some kind of streaming channel.

**Comment by edublancas** [comment]
It is technically possible to use YASS online but it is not designed to be used that way. The strength of YASS is to use all the data available, triage "clear spikes" and use those to later deal with the rest of the spikes. It would be possible to serialize YASS models to later use them in an online fashion but we are not currently pursuing that direction. You are welcome to collaborate.

We fixed the `ValueError: could not broadcast input array from shape (50000,5,10) into shape (1239,5,10)`. The fix is now in the master branch.

**Comment by JohnV7** [comment]
thanks for the fix. I would be interested in contributing for the online sorting, but first I need to find some time to read and understand the paper.
