### ISSUE TITLE
issues with examples in the docs: wrong number of arguments

### ISSUE THREAD

**Issue by pplenck** [paninski-lab/yass#289]
HI
I've been trying to run yass and found a couple of bugs in the examples given in the doc from dec 05, 2018
for instance, on  pp 18-19

standarized_path, standarized_params, whiten_filter = preprocess.run()
(spike_index_clear,
 spike_index_all) = detect.run(standarized_path,
                               standarized_params,
                               whiten_filter)
should be replaced by :

(standarized_path, standarized_params, channel_index, whiten_filter) = preprocess.run()
(clear_scores, spike_index_clear, spike_index_all) = detect.run(standarized_path,           standarized_params, channel_index, whiten_filter)

at least that's what I get from the run.py files
bests
PP

**Comment by pplenck** [comment]
Thanks, I just can't get the master version, for some reason visual studio 14.0 returns an error:

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2,

I think I'll throw my PC by the window and install linux in a brand new one

**Comment by pplenck** [comment]
I actually installed  Visual studio again 
now I get: 
 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
should I open a new issue?

**Comment by catubc** [comment]
Hi pplenck.  Sorry for the delay in response.  

We have now pushed updated (relatively stable) code into the master branch.  You should try running that version in the future.

Re: visual studio issues, I know there are some tricky issues, but at this time we are not providing windows support due to limited resources on our end.  Your best bet is to check the stack overflow discussion threads.
