### ISSUE TITLE
NN vs threshold?

### ISSUE THREAD

**Issue by weallen** [paninski-lab/yass#29]
Hi,

I have a lot of data generated using Neuropixels. I'd like to try YASS, but I'd imagine that the pre-trained spike detection neural network may not work as it did in the initial publication, given that it seemed to have been trained on MEA retina data. How does performance with the neural network compare with just using spike thresholding? Is it difficult to train a new spike detection network on the data I've already sorted, and how well does it generalize?

**Comment by edublancas** [comment]
Hi, we have a tutorial for training a neural network here:

https://github.com/paninski-lab/yass-examples/blob/master/NN_training_tutorial.ipynb

How big is your data? We are currently working on improving YASS performance to make it feasible to run it on larger-than-memory datasets.

**Comment by weallen** [comment]
Hi,
This doesn't really answer my question -- how much data do you need for training, and how does using the neural network compare with just spike thresholding?

**Comment by jinhyunglee** [comment]
Hello,
We use augmentation to create training data. Given templates (E.I. of each neurons), it generates fake spikes (training data) by varying size and noise. 
So, the more proper question would be how many "good" templates do you need?
I would say the more is the better but as long as your set of templates cover most possible E.I.'s, I would say you are good.

NN vs. threshold:
I would say NN does much better job. 
1. better alignment: no split clusters because of alignment issue
2. no templates that look like collision
3. better speed. 

I hope this answer your question.
